---
title: "Bios_26211"
output: html_document
date: "2025-03-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include=FALSE, echo = FALSE, warning=FALSE,message=FALSE)
options(prType='html')

### Uncomment this if the first time, otherwise leave commented
#install.packages('nhanesA')
#install.packages('foreign')

#install.packages("devtools")
#devtools::install_github("dayoonkwon/BioAge")

library(foreign)
library(nhanesA)
library(tidyverse)
library(gridExtra)
library(broom)
require(rms)
library(ggplot2)
library(naniar)
library(mosaic)
require(dplyr)
require(brms)
library(pROC)
library(AUC)
library(viridis)
library(BioAge) 
library(dplyr)
```


```{r}
hd_nhanes = function(biomarkers) {

  #develop training dataset for HD
  train = NHANES3 %>%
    filter(age >= 20 & age <= 30 & pregnant == 0 & bmi < 30) %>%
    mutate(albumin = ifelse(albumin >= 3.5 & albumin <= 5, albumin, NA),
           albumin_gL = ifelse(is.na(albumin), NA, albumin_gL),
           alp = ifelse(gender == 2, ifelse(alp >= 37 & alp <= 98, alp, NA), ifelse(alp >= 45 & alp <= 115, alp, NA)),
           lnalp = ifelse(is.na(alp), NA, lnalp),
           bap = ifelse(gender == 2, ifelse(bap <= 14, bap, NA), ifelse(bap <= 20, bap, NA)),
           bun = ifelse(gender == 2, ifelse(bun >= 6 & bun <= 21, bun, NA), ifelse(bun >= 8 & bun <= 24, bun, NA)),
           lnbun = ifelse(is.na(bun), NA, lnbun),
           creat = ifelse(gender == 2, ifelse(creat >= 0.6 & creat <= 1.1, creat, NA), ifelse(creat >= 0.8 & creat <= 1.3, creat, NA)),
           creat_umol = ifelse(is.na(creat), NA, creat_umol),
           lncreat = ifelse(is.na(creat), NA, lncreat),
           lncreat_umol = ifelse(is.na(creat), NA, lncreat_umol),
           glucose = ifelse(glucose >= 60 & glucose <= 100, glucose, NA),
           glucose_mmol = ifelse(is.na(glucose), NA, glucose_mmol),
           glucose_fasting = ifelse(glucose_fasting >= 65 & glucose_fasting <= 110, glucose_fasting, NA),
           ttbl = ifelse(ttbl >= 0.1 & ttbl <= 1.4, ttbl, NA),
           uap = ifelse(gender == 2, ifelse(uap >= 2 & uap <= 7, uap, NA), ifelse(uap >= 2.1 & uap <= 8.5, uap, NA)),
           lnuap = ifelse(is.na(uap), NA, lnuap),
           basopa = ifelse(basopa >= 0 & basopa <= 2, basopa, NA),
           eosnpa = ifelse(eosnpa >=1 & eosnpa <= 7, eosnpa, NA),
           mcv = ifelse(gender == 2, ifelse(mcv >= 78 & mcv <= 101, mcv, NA), ifelse(mcv >= 82 & mcv <= 102, mcv, NA)),
           monopa = ifelse(monopa >= 3 & monopa <= 10, monopa, NA),
           neut = ifelse(neut >= 45 & neut <= 74, neut, NA),
           rbc = ifelse(gender == 2, ifelse(rbc >= 3.5 & rbc <= 5.5, rbc, NA), ifelse(rbc >= 4.2 & rbc <= 6.9, rbc, NA)),
           rdw = ifelse(rdw >= 11.5 & rdw <= 14.5, rdw, NA),
           cadmium = ifelse(cadmium >= 2.7 & cadmium <= 10.7, cadmium, NA),
           crp = ifelse(crp < 2, crp, NA),
           crp_cat = ifelse(is.na(crp), NA, crp_cat),
           lncrp = ifelse(is.na(crp), NA, lncrp),
           cyst = ifelse(cyst >= 0.51 & cyst <= 0.98, cyst, NA),
           ggt = ifelse(gender == 2, ifelse(ggt <= 37.79, ggt, NA), ifelse(ggt <= 55.19, ggt, NA)),
           insulin = ifelse(insulin >= 2.52 & insulin <= 24.1, insulin, NA),
           hba1c = ifelse(hba1c >= 4 & hba1c <= 5.6, hba1c, NA),
           lnhba1c = ifelse(is.na(hba1c), NA, lnhba1c),
           hdl = ifelse(gender == 2, ifelse(hdl >= 40 & hdl <= 86, hdl, NA), ifelse(hdl >= 35 & hdl <= 80, hdl, NA)),
           ldl = ifelse(ldl >= 80 & ldl <= 130, ldl, NA),
           trig = ifelse(trig >= 54 & trig <= 110, trig, NA),
           lymph = ifelse(lymph >= 20 & lymph <= 40, lymph, NA),
           wbc = ifelse(wbc >= 4.5 & wbc <= 11, wbc, NA),
           uap = ifelse(gender == 2, ifelse(uap >= 2.7 & uap <= 6.3, uap, NA), ifelse(uap >= 3.7 & uap <= 8, uap, NA)),
           sbp = ifelse(sbp < 120, sbp, NA),
           dbp = ifelse(dbp < 80, dbp, NA),
           meanbp = ifelse(meanbp < 93.33, meanbp, NA),
           pulse = ifelse(pulse >= 60 & pulse <= 100, pulse, NA),
           totchol = ifelse(totchol < 200, totchol, NA),
           fev = ifelse(fev >= mean(fev, na.rm = TRUE) * 0.8, fev, NA),
           fev_1000 = ifelse(is.na(fev), NA, fev_1000),
           vitaminA = ifelse(vitaminA >= 1.05 & vitaminA <= 2.27, vitaminA, NA),
           vitaminE = ifelse(vitaminE <= 28, vitaminE, NA),
           vitaminB12 = ifelse(vitaminB12 >= 100 & vitaminB12 <= 700, vitaminB12, NA),
           vitaminC = ifelse(vitaminC >= 23 & vitaminC <= 85, vitaminC, NA))

  #calculate hd
  hd_fem = hd_calc(data = NHANES4 %>%
                     filter(gender == 2),
                   reference = train %>%
                     filter(gender == 2),
                   biomarkers)

  hd_male = hd_calc(data = NHANES4 %>%
                     filter(gender == 1),
                   reference = train %>%
                     filter(gender == 1),
                   biomarkers)

  dat = rbind(hd_fem$data, hd_male$data)

  dat = left_join(NHANES4, dat[,c("sampleID","hd","hd_log")], by= "sampleID")
  fit = list(female = hd_fem$fit, male = hd_male$fit, nobs = hd_fem$fit$nobs + hd_male$fit$nobs)

  hd = list(data = dat, fit = fit)
  class(hd) = append(class(hd),'hd')
  return(hd)
}
```


```{r}
kdm_nhanes = function (biomarkers) {

  #calculate training KDM
  train_fem = kdm_calc(data = NHANES3 %>%
                         filter(age >= 30 & age <= 75 & pregnant == 0, gender == 2),
                       biomarkers, fit = NULL, s_ba2 = NULL)
  train_male = kdm_calc(data = NHANES3 %>%
                          filter(age >= 30 & age <= 75 & pregnant == 0, gender == 1),
                        biomarkers, fit = NULL, s_ba2 = NULL)

  #calculate test modified KDM
  test_fem = kdm_calc(data = NHANES4 %>%
                        filter(gender == 2),
                      biomarkers, fit = train_fem$fit, s_ba2 = train_fem$fit$s_ba2)
  test_male = kdm_calc(data = NHANES4 %>%
                         filter(gender == 1),
                       biomarkers, fit = train_male$fit, s_ba2 = train_male$fit$s_ba2)

  #combine calculated kdm
  test = rbind(test_fem$data, test_male$data)

  #combine data
  dat = left_join(NHANES4, test[,c("sampleID", "kdm", "kdm_advance")], by = "sampleID")
  fit = list(female = train_fem$fit, male = train_male$fit, nobs = test_fem$fit$nobs + test_male$fit$nobs)

  kdm = list(data = dat, fit = fit)
  class(kdm) = append(class(kdm), "kdm")
  return(kdm)

}

```

```{r}
phenoage_nhanes = function(biomarkers) {

  #develop training dataset for Levine's phenoage method
  train = phenoage_calc(data = NHANES3 %>%
                          filter(age >= 20 & age <= 84) %>%
                          mutate(albumin = albumin_gL,
                                 glucose = glucose_mmol,
                                 creat = creat_umol,
                                 lncreat = lncreat_umol),
                        biomarkers, fit=NULL)

  #develop test dataset for Levine's phenoage method
  test = phenoage_calc(data = NHANES4 %>%
                         filter(age >= 20) %>%
                         mutate(albumin = albumin_gL,
                                glucose = glucose_mmol,
                                creat = creat_umol,
                                lncreat = lncreat_umol),
                       biomarkers, fit=train$fit)

  #comebine calculated phenoage
  dat = left_join(NHANES4, test$data[,c("sampleID", "phenoage", "phenoage_advance")], by = "sampleID")

  phenoage = list(data = dat, fit = train$fit)
  class(phenoage) = append(class(phenoage), "phenoage")
  return(phenoage)


}

```


```{r}

#HD using NHANES (separate training for men and women)
hd = hd_nhanes(biomarkers=c("albumin","alp","lncrp","totchol","lncreat","hba1c","sbp","bun","uap","lymph","mcv","wbc"))

#KDM bioage using NHANES (separate training for men and women)
kdm = kdm_nhanes(biomarkers=c("albumin","alp","lncrp","totchol","lncreat","hba1c","sbp","bun","uap","lymph","mcv","wbc"))

#phenoage using NHANES
phenoage = phenoage_nhanes(biomarkers=c("albumin_gL","alp","lncrp","totchol","lncreat_umol","hba1c","sbp","bun","uap","lymph","mcv","wbc"))

```


```{r}

#assemble NHANES IV dataset with projected biological aging measures for analysis
data = merge(hd$data, kdm$data) %>% merge(., phenoage$data)

```


```{r}


#select biological age variables
agevar = c("kdm0","phenoage0","kdm","phenoage","hd","hd_log")

#prepare labels
label = c("KDM\nBiological Age",
          "Levine\nPhenotypic Age",
          "Modified-KDM\nBiological Age",
          "Modified-Levine\nPhenotypic Age",
          "Homeostatic\nDysregulation",
          "Log\nHomeostatic\nDysregulation")

#plot age vs bioage
plot_ba(data, agevar, label)

```
```{r}
#select biological age variables
agevar = c("kdm_advance0","phenoage_advance0","kdm_advance","phenoage_advance","hd","hd_log")

#prepare labels
#values should be formatted for displaying along diagonal of the plot
#names should be used to match variables and order is preserved
label = c(
  "kdm_advance0"="KDM\nBiological Age\nAdvancement",
  "phenoage_advance0"="Levine\nPhenotypic Age\nAdvancement",
  "kdm_advance"="Modified-KDM\nBiological Age\nAdvancement",
  "phenoage_advance"="Modified-Levine\nPhenotypic Age\nAdvancement",
  "hd" = "Homeostatic\nDysregulation",
  "hd_log" = "Log\nHomeostatic\nDysregulation")

#use variable name to define the axis type ("int" or "float")
axis_type = c(
  "kdm_advance0"="float",
  "phenoage_advance0"="float",
  "kdm_advance"="float",
  "phenoage_advance"="flot",
  "hd"="flot",
  "hd_log"="float")

#plot BAA corplot
plot_baa(data,agevar,label,axis_type)
```
