
---
title: "Tara's HD Analysis"
author: "Your Name"
date: "`r Sys.Date()`"
output: html_document
---
install.packages("tidyverse")
library(tidyverse)   # lets me get the data
install.packages("dplyr")
library(dplyr)       # lets me edit the data
install.packages("ggcorrplot")
library(ggcorrplot)  # for the heatmaps
install.packages("caret")
library(caret)       # in case of missing data
install.packages("MASS")
library(MASS) #regression
install.packages("cli")
library(cli)

load("/Users/kedda/Downloads/bios26211projectfinal/NHANES3_HDTrain.rda")
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES3.rda")
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES4.rda")

#load bioage
install.packages("devtools")
devtools::install_github("dayoonkwon/BioAge")
library(BioAge)

# checking if there's missing vals
colSums(is.na(NHANES4))
#there ended up being a ton, so now I am going to compute the percent that is missing from each so I can choose only those that have enough data.
missing_perc <- colSums(is.na(NHANES4)) / nrow(NHANES4)
print(missing_perc)
#looking at data visually, I decided that those with over 10% missing should be excluded from the biomarkers chosen
NHANES4_filtered <- NHANES4[, missing_perc < 0.1]
str(NHANES4_filtered)

NHANES3_filtered <- NHANES3[, missing_perc < 0.1]
str(NHANES3_filtered)
#from these lists, I picked out all data that was listed as a "biomarker" in the dataset and then also age (chronological age) since it would be valuable to have that in the dataset later when we compare the determined biological age to chronological age

#below are the biomarkers i chose. i had to exclude "neut" since even though it showed up as being <10% for NHANES3, it also only had NA in it so I got rid of it. see attached README for what each of these variables mean.
biomarkers_with_age <- c("age","lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "meanbp", "pulse", "phpfast")



# impute NHANES4 and NHANES3 with means (basically replaces all the NA vals with mean for that so the program doesn't get confused during analysis)
NHANES4_imputed <- NHANES4
for (col in biomarkers_with_age) {
  if (col %in% colnames(NHANES4_imputed)) {  # Ensure column exists
    NHANES4_imputed[[col]][is.na(NHANES4_imputed[[col]])] <- mean(NHANES4_imputed[[col]], na.rm = TRUE)
  }
}
NHANES3_imputed <- NHANES3
for (col in biomarkers_with_age) {
  if (col %in% colnames(NHANES3_imputed)) {  # Ensure column exists
    NHANES3_imputed[[col]][is.na(NHANES3_imputed[[col]])] <- mean(NHANES3_imputed[[col]], na.rm = TRUE)
  }
}


hd_result <- hd_calc(NHANES4_imputed, NHANES3_imputed, biomarkers_with_age)
hd_data <- hd_result$data

#this is the data with JUST the biomarkers I want
hd_data_filtered <- hd_data[, biomarkers_with_age]
head(hd_data_filtered)



biomarkers <- c("lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "meanbp", "pulse", "phpfast")

NHANES4_imfil <- NHANES4_imputed
NHANES4_imfil <- NHANES4_imfil[, biomarkers]
head(NHANES4_imfil)

NHANES3_imfil <- NHANES3_imputed
NHANES3_imfil <- NHANES3_imfil[, biomarkers]
head(NHANES3_imfil)

#scaling data so can use it for PCA and matrix analysis BUT since NHANES4 is trained on NHANES3 and also I just want to standardize it, I'm using the means/SDs from NHANES3 to scale it
NHANES3_stats <- list()

for (col in biomarkers_with_age) {
  NHANES3_stats[[col]] <- list(
    mean = mean(NHANES3_imputed[[col]], na.rm = TRUE),
    sd = sd(NHANES3_imputed[[col]], na.rm = TRUE)
  )
}

NHANES3_scaled <- NHANES3_imfil
NHANES4_scaled <- NHANES4_imfil

for (col in biomarkers) {
  NHANES3_scaled[[col]] <- (NHANES3_scaled[[col]] - NHANES3_stats[[col]]$mean) / NHANES3_stats[[col]]$sd
  NHANES4_scaled[[col]] <- (NHANES4_scaled[[col]] - NHANES3_stats[[col]]$mean) / NHANES3_stats[[col]]$sd
}
head(NHANES4_scaled)

#now that it's scaled, making a correlation matrix so i can see which are most correlated, used claude and https://cran.r-project.org/web/packages/ggcorrplot/readme/README.html to help with formatting
cor_matrix <- cor(NHANES4_scaled[, biomarkers])
ggcorrplot(cor_matrix, method = "square", type = "lower", lab = TRUE, outline.color = "black", colors = c("#009e73", "white", "#cc79a7"), title = "Correlation Matrix for Biomarkers With <10% Missing Data")




#ok so now that the correlation matrix is done, I will use PCA

install.packages("FactoMineR")
library(FactoMineR)  # PCA
install.packages("factoextra")
library(factoextra)  # PCA

#this line calculates the PCA
pca_res <- PCA(NHANES4_scaled[, biomarkers], scale.unit = TRUE, graph = FALSE)
#identifies top 4 contributing biomarkers

top_4_PCA <- names(sort(pca_res$var$contrib[,1], decreasing = TRUE))[1:4]
print(top_4_PCA)
#this function is annoying and it doesn't let me label the dimensions, so i will do that manuallly
fviz_eig(pca_res, title = "Scree Plot of BioMarkers", add_labels = TRUE)
top_10_PCA <- names(sort(pca_res$var$contrib[,1], decreasing = TRUE))[1:10]
print(top_10_PCA)

#forward model!
install.packages("MASS", repos="http://cran.us.r-project.org")
library(MASS)

biomarkers <- c("lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "meanbp", "pulse", "phpfast")

NHANES4_scaled <- NHANES4_imputed
for (col in biomarkers) {
  NHANES4_scaled[[col]] <- scale(NHANES4_scaled[[col]])
}

head(NHANES4_scaled)

full_model <- lm(kdm0 ~ ., data = NHANES4_scaled[, c("kdm0", biomarkers)])

step_model <- stepAIC(full_model, direction = "forward")

summary(step_model)

#from the summary, we see that the significant biomarkers are lymph, mcv, rbc, rdw, wbc, sbp, and phpfast. the insignificant biomarkers are dbp, meanbp, and pulse. now, I want to reform their plots for their three methods of determining biological age

#this following section is partially adapted from https://github.com/dayoonkwon/BioAge/blob/master/README.md 

library(BioAge)
library(dplyr)


#setting it so it trains on both ALL of the biomarkers, the PCA top 4, also just the top contributors
biomarkers_all <- c("lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "meanbp", "pulse", "phpfast")

#these are the top 7 biomarkers from the PCA output (I picked 7 since then that's equivalent to number significant)
biomarkers_PCA <- c("meanbp", "sbp", "dbp", "pulse", "rbc", "rdw", "mcv")

#these are the top 7 significant forward
biomarkers_FF <- c("lymph", "mcv", "rbc", "rdw", "wbc", "sbp", "phpfast")

#these are the biomarkers that are not correlated based on the correlation matrix
biomarkers_corr <- c("lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "phpfast")


#training the models 

#HD was skipped, since it requires all biomarkers to be present

#KDM bioage using NHANES (separate training for men and women)

#all
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES3.rda")
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES4.rda")
biomarkers_with_age <- c("age","lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "meanbp", "pulse", "phpfast")

NHANES4_imputed <- NHANES4
for (col in biomarkers_with_age) {
  if (col %in% colnames(NHANES4_imputed)) { 
    NHANES4_imputed[[col]][is.na(NHANES4_imputed[[col]])] <- mean(NHANES4_imputed[[col]], na.rm = TRUE)
  }
}
NHANES3_imputed <- NHANES3
for (col in biomarkers_with_age) {
  if (col %in% colnames(NHANES3_imputed)) { 
    NHANES3_imputed[[col]][is.na(NHANES3_imputed[[col]])] <- mean(NHANES3_imputed[[col]], na.rm = TRUE)
  }
}

biomarkers_with_age_preg <- c("sampleID", "age","pregnant", "gender", "lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "meanbp", "pulse", "phpfast")

NHANES4_all <- NHANES4_imputed
NHANES4_all <- NHANES4_all[, biomarkers_with_age_preg]
head(NHANES4_all)

NHANES3_all <- NHANES3_imputed
NHANES3_all <- NHANES3_all[, biomarkers_with_age_preg]
head(NHANES3_all)


NHANES4 <- NHANES4_all
NHANES3 <- NHANES3_all
kdm_all <- kdm_nhanes(biomarkers = biomarkers_all)


#PCA
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES3.rda")
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES4.rda")
biomarkers_with_age_PCA <- c("age", "meanbp", "sbp", "dbp", "pulse", "rbc", "rdw", "mcv")

NHANES4_imputed <- NHANES4
for (col in biomarkers_with_age_PCA) {
  if (col %in% colnames(NHANES4_imputed)) { 
    NHANES4_imputed[[col]][is.na(NHANES4_imputed[[col]])] <- mean(NHANES4_imputed[[col]], na.rm = TRUE)
  }
}
NHANES3_imputed <- NHANES3
for (col in biomarkers_with_age_PCA) {
  if (col %in% colnames(NHANES3_imputed)) {
    NHANES3_imputed[[col]][is.na(NHANES3_imputed[[col]])] <- mean(NHANES3_imputed[[col]], na.rm = TRUE)
  }
}

biomarkers_with_age_preg_PCA <- c("sampleID", "age","pregnant", "gender", "meanbp", "sbp", "dbp", "pulse", "rbc", "rdw", "mcv")

NHANES4_PCA <- NHANES4_imputed
NHANES4_PCA <- NHANES4_PCA[, biomarkers_with_age_preg_PCA]
head(NHANES4_PCA)

NHANES3_PCA <- NHANES3_imputed
NHANES3_PCA <- NHANES3_PCA[, biomarkers_with_age_preg_PCA]
head(NHANES3_PCA)

NHANES4 <- NHANES4_PCA
NHANES3 <- NHANES3_PCA
kdm_PCA <- kdm_nhanes(biomarkers = biomarkers_PCA)

#forward model
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES3.rda")
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES4.rda")
biomarkers_with_age_FF <- c("age", "lymph", "mcv", "rbc", "rdw", "wbc", "sbp", "phpfast")

NHANES4_imputed <- NHANES4
for (col in biomarkers_with_age_FF) {
  if (col %in% colnames(NHANES4_imputed)) { 
    NHANES4_imputed[[col]][is.na(NHANES4_imputed[[col]])] <- mean(NHANES4_imputed[[col]], na.rm = TRUE)
  }
}
NHANES3_imputed <- NHANES3
for (col in biomarkers_with_age_FF) {
  if (col %in% colnames(NHANES3_imputed)) {
    NHANES3_imputed[[col]][is.na(NHANES3_imputed[[col]])] <- mean(NHANES3_imputed[[col]], na.rm = TRUE)
  }
}

biomarkers_with_age_preg_FF <- c("sampleID","age","pregnant", "gender", "lymph", "mcv", "rbc", "rdw", "wbc", "sbp", "phpfast")

NHANES4_FF <- NHANES4_imputed
NHANES4_FF <- NHANES4_FF[, biomarkers_with_age_preg_FF]
head(NHANES4_FF)

NHANES3_FF <- NHANES3_imputed
NHANES3_FF <- NHANES3_FF[, biomarkers_with_age_preg_FF]
head(NHANES3_FF)

NHANES4 <- NHANES4_FF
NHANES3 <- NHANES3_FF
kdm_FF <- kdm_nhanes(biomarkers = biomarkers_FF)

#correlation matrix
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES3.rda")
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES4.rda")

#for this, we will drop meanbp and pulse, as there is one per pair
biomarkers_with_age_corr <- c("age","lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "phpfast")

NHANES4_imputed <- NHANES4
for (col in biomarkers_with_age_corr) {
  if (col %in% colnames(NHANES4_imputed)) { 
    NHANES4_imputed[[col]][is.na(NHANES4_imputed[[col]])] <- mean(NHANES4_imputed[[col]], na.rm = TRUE)
  }
}
NHANES3_imputed <- NHANES3
for (col in biomarkers_with_age_corr) {
  if (col %in% colnames(NHANES3_imputed)) {
    NHANES3_imputed[[col]][is.na(NHANES3_imputed[[col]])] <- mean(NHANES3_imputed[[col]], na.rm = TRUE)
  }
}




biomarkers_with_age_preg_corr <- c("sampleID","age","pregnant", "gender", "lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "phpfast")

NHANES4_corr <- NHANES4_imputed
NHANES4_corr <- NHANES4_corr[, biomarkers_with_age_preg_corr]
head(NHANES4_corr)

NHANES3_corr <- NHANES3_imputed
NHANES3_corr <- NHANES3_corr[, biomarkers_with_age_preg_corr]
head(NHANES3_corr)

NHANES4 <- NHANES4_corr
NHANES3 <- NHANES3_corr
kdm_corr <- kdm_nhanes(biomarkers = biomarkers_corr)

#used claude for help with merging step, turns out you can only merge 2 at a time?
kdm_data <- merge(kdm_all$data, kdm_PCA$data, by = "sampleID", suffixes = c("_all", "_PCA"))
kdm_data <- merge(kdm_data, kdm_FF$data, by = "sampleID", suffixes = c("", "_forward"))
kdm_data <- merge(kdm_data, kdm_corr$data, by = "sampleID", suffixes = c("", "_corr"))

colnames(kdm_data)[which(colnames(kdm_data) == "kdm")] <- "kdm_FF"
colnames(kdm_data)[which(colnames(kdm_data) == "kdm_corr")] <- "kdm_corr"

agevar <- c("kdm_all", "kdm_PCA", "kdm_FF", "kdm_corr")

label = c("All Biomarkers",
          "Top 7 Biomarkers from PCA",
          "Top 7 Biomarkers from Forward Model", "Correlation Reduced Model")
          
par(pin = c(24, 4))
plot_ba(kdm_data, agevar, label)

#phenoage using NHANES

#changed function so it would allow me to use just my biomarkers -> ended up having to scrap since the PCA biomarkers kept breaking RStudio and decided that KDM would be sufficient to show improvement, especially since KDM originally gave the least variable output of the three models


<!--
phenoage_nhanes <- function(biomarkers) {
    train = phenoage_calc(
        data = NHANES3 %>% filter(age >= 20 & age <= 84) %>%
          select(sampleID, all_of(biomarkers)),
        biomarkers,
        fit = NULL
    )
    test = phenoage_calc(
        data = NHANES4 %>% filter(age >= 20) %>%
          select(sampleID, all_of(biomarkers)),
        biomarkers,
        fit = train$fit
    )
    dat = left_join(NHANES4, test$data[, c("sampleID", "phenoage", "phenoage_advance")], by = "sampleID")
    phenoage = list(data = dat, fit = train$fit)
    class(phenoage) = append(class(phenoage), "phenoage")
    return(phenoage)
}


#all
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES3.rda")
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES4.rda")
biomarkers_with_age <- c("age","lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "meanbp", "pulse", "phpfast")

NHANES4_imputed <- NHANES4
for (col in biomarkers_with_age) {
  if (col %in% colnames(NHANES4_imputed)) { 
    NHANES4_imputed[[col]][is.na(NHANES4_imputed[[col]])] <- mean(NHANES4_imputed[[col]], na.rm = TRUE)
  }
}
NHANES3_imputed <- NHANES3
for (col in biomarkers_with_age) {
  if (col %in% colnames(NHANES3_imputed)) { 
    NHANES3_imputed[[col]][is.na(NHANES3_imputed[[col]])] <- mean(NHANES3_imputed[[col]], na.rm = TRUE)
  }
}

biomarkers_with_age_preg <- c("sampleID", "age","status","time", "gender", "lymph", "mcv", "rbc", "rdw", "wbc", "dbp","sbp", "meanbp", "pulse", "phpfast")

NHANES4_all <- NHANES4_imputed
NHANES4_all <- NHANES4_all[, biomarkers_with_age_preg]
head(NHANES4_all)

NHANES3_all <- NHANES3_imputed
NHANES3_all <- NHANES3_all[, biomarkers_with_age_preg]
head(NHANES3_all)


NHANES4 <- NHANES4_all
NHANES3 <- NHANES3_all
phenoage_all <- phenoage_nhanes(biomarkers = biomarkers_with_age_preg)

#PCA
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES3.rda")
load("/Users/kedda/Downloads/bios26211projectfinal/NHANES4.rda")
biomarkers_with_age_PCA <- c("age", "meanbp", "sbp", "dbp", "pulse", "rbc", "rdw", "mcv")

NHANES4_imputed <- NHANES4
for (col in biomarkers_with_age_PCA) {
  if (col %in% colnames(NHANES4_imputed)) { 
    NHANES4_imputed[[col]][is.na(NHANES4_imputed[[col]])] <- mean(NHANES4_imputed[[col]], na.rm = TRUE)
  }
}
NHANES3_imputed <- NHANES3
for (col in biomarkers_with_age_PCA) {
  if (col %in% colnames(NHANES3_imputed)) {
    NHANES3_imputed[[col]][is.na(NHANES3_imputed[[col]])] <- mean(NHANES3_imputed[[col]], na.rm = TRUE)
  }
}

biomarkers_with_age_preg_PCA <- c("sampleID", "age","status","time", "gender", "meanbp", "sbp", "dbp", "pulse", "rbc", "rdw", "mcv")

NHANES4_PCA <- NHANES4_imputed
NHANES4_PCA <- NHANES4_PCA[, biomarkers_with_age_preg_PCA]
head(NHANES4_PCA)

NHANES3_PCA <- NHANES3_imputed
NHANES3_PCA <- NHANES3_PCA[, biomarkers_with_age_preg_PCA]
head(NHANES3_PCA)

NHANES4 <- NHANES4_PCA
NHANES3 <- NHANES3_PCA
phenoage_PCA <- phenoage_nhanes(biomarkers = biomarkers_with_age_preg_PCA)
-->

